### PR TITLE
Ignore nomodifiable files

### LINKED ISSUE #22: Do not apply changes to `'nomodifiable'` buffers

### PR DESCRIPTION
**Pull request by hauleth**
Close #22

### CODE REVIEW

**Comment by mcepl** [comment]
LGTM 👍

**Comment by sgur** [comment]
Thank you!

**Comment by Carpetsmoker** [comment]
I'm interested what the reason for this is @hauleth? It seems to me that the various display settings – such as tab_stop – should still be applied?

**Comment by hauleth** [comment]
@Carpetsmoker now I do not remember what was the problem I had there to be honest.

**Pull request merged**
